// Auth Const
export const USER_LOADED_SUCCESS = 'user_loaded';
export const USER_LOADING = 'user_loading';
export const LOGIN_SUCCESS = "login_success";
export const LOGIN_FAIL = "login_fail";
export const LOGOUT_SUCCESS = "logout_success";
export const LOGOUT= "logout";
export const AUTH_ERROR = "auth_error";
export const REGISTER_FAIL = "register_fail";
export const REGISTER_SUCCESS = "register_success";
export const SHOW_MESSAGE = "show_message";

// billing address
export const CREATE_BILLING_ADDRESS_SUCCESS = 'CREATE_BILLING_ADDRESS_SUCCESS';
export const CREATE_BILLING_ADDRESS_FAILS = 'CREATE_BILLING_ADDRESS_FAILS';
export const FETCH_BILLING_ADDRESS_SUCCESS = 'FETCH_BILLING_ADDRESS_SUCCESS';
export const FETCH_BILLING_ADDRESS_FAILS = 'FETCH_BILLING_ADDRESS_FAILS';
export const UPDATE_BILLING_ADDRESS_SUCCESS = 'UPDATE_BILLING_ADDRESS_SUCCESS';
export const UPDATE_BILLING_ADDRESS_FAILS = 'UPDATE_BILLING_ADDRESS_FAILS';
export const GET_SINGLE_BILLING_ADDRESS_SUCCESS = 'GET_SINGLE_BILLING_ADDRESS_SUCCESS';
export const GET_SINGLE_BILLING_ADDRESS_FAILS = 'GET_SINGLE_BILLING_ADDRESS_FAILS';

// shipping address
export const CREATE_SHIPPING_ADDRESS_SUCCESS = 'CREATE_SHIPPING_ADDRESS_SUCCESS';
export const CREATE_SHIPPING_ADDRESS_FAILS = 'CREATE_SHIPPING_ADDRESS_FAILS';
export const UPDATE_SHIPPING_ADDRESS_SUCCESS = 'UPDATE_SHIPPING_ADDRESS_SUCCESS';
export const UPDATE_SHIPPING_ADDRESS_FAILS = 'UPDATE_SHIPPING_ADDRESS_FAILS';
export const FETCH_SHIPPING_ADDRESS_SUCCESS = 'FETCH_SHIPPING_ADDRESS_SUCCESS';
export const FETCH_SHIPPING_ADDRESS_FAILS = 'FETCH_SHIPPING_ADDRESS_FAILS';
export const GET_SINGLE_SHIPPING_ADDRESS_SUCCESS = 'GET_SINGLE_SHIPPING_ADDRESS_SUCCESS';
export const GET_SINGLE_SHIPPING_ADDRESS_FAILS = 'GET_SINGLE_SHIPPING_ADDRESS_FAILS';
export const SHOW_FORM = 'SHOW_FORM';
